
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select the correct spelling','C','{"A":"Accomodate","B":"Acommodate","C":"Accommodate","D":"Acomodate"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '2 + 2 × 2 = ?','B','{"A":"8","B":"6","C":"4","D":"10"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option C','C','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Find next: 3, 6, 12, 24, ?','B','{"A":"36","B":"48","C":"60","D":"72"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which is a fruit?','C','{"A":"Carrot","B":"Potato","C":"Apple","D":"Onion"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which word is different?','D','{"A":"Dog","B":"Cat","C":"Cow","D":"Chair"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'How many vowels in EDUCATION?','B','{"A":"4","B":"5","C":"6","D":"3"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct sentence?','B','{"A":"He go to school","B":"He goes to school","C":"He going school","D":"He gone school"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Number repeated: 1,2,3,2,5','B','{"A":"1","B":"2","C":"3","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Tomorrow after Monday?','B','{"A":"Sunday","B":"Tuesday","C":"Wednesday","D":"Friday"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option A','A','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '5 × 3 + 2 = ?','A','{"A":"17","B":"25","C":"15","D":"13"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Find next: 1,4,9,16,?','C','{"A":"20","B":"24","C":"25","D":"30"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling?','B','{"A":"Seperate","B":"Separate","C":"Seprate","D":"Seperete"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one out','D','{"A":"Pen","B":"Pencil","C":"Book","D":"Car"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '7 + 3 × 2 = ?','B','{"A":"20","B":"13","C":"14","D":"16"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option D','D','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'How many letters in APPLE?','B','{"A":"4","B":"5","C":"6","D":"3"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Opposite of Hot','A','{"A":"Cold","B":"Warm","C":"Cool","D":"Heat"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 10,20,30,?','B','{"A":"35","B":"40","C":"50","D":"60"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Enviroment","B":"Environment","C":"Enviornment","D":"Envirnment"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '3+3×3=?','B','{"A":"18","B":"12","C":"9","D":"15"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option B','B','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 2,5,10,17,?','B','{"A":"24","B":"26","C":"28","D":"30"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which is animal?','B','{"A":"Car","B":"Dog","C":"Chair","D":"Pen"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Red","B":"Blue","C":"Green","D":"Table"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Vowels in INDIA?','B','{"A":"2","B":"3","C":"4","D":"1"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct sentence','B','{"A":"She go","B":"She goes","C":"She going","D":"She gone"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Repeat number: 4,5,6,5,7','B','{"A":"4","B":"5","C":"6","D":"7"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Day after Tuesday?','B','{"A":"Monday","B":"Wednesday","C":"Friday","D":"Sunday"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option A','A','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '6×2+3=?','B','{"A":"12","B":"15","C":"18","D":"9"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 4,8,16,?','B','{"A":"24","B":"32","C":"64","D":"20"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Occured","B":"Occurred","C":"Ocurred","D":"Occerred"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','C','{"A":"Apple","B":"Banana","C":"Carrot","D":"Mango"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '9+3×2=?','B','{"A":"24","B":"15","C":"18","D":"12"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option C','C','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Letters in CAT','B','{"A":"2","B":"3","C":"4","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Opposite of Big','C','{"A":"Large","B":"Huge","C":"Small","D":"Tall"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 5,15,25,?','B','{"A":"30","B":"35","C":"40","D":"45"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Recieve","B":"Receive","C":"Receeve","D":"Recive"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '8+2×3=?','B','{"A":"30","B":"14","C":"24","D":"20"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option D','D','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 1,2,4,8,?','C','{"A":"10","B":"12","C":"16","D":"20"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which is vegetable?','C','{"A":"Apple","B":"Banana","C":"Carrot","D":"Mango"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Dog","B":"Cat","C":"Lion","D":"Table"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Vowels in HELLO?','B','{"A":"1","B":"2","C":"3","D":"4"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct sentence','B','{"A":"They is","B":"They are","C":"They am","D":"They be"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Repeat number: 2,3,4,3,5','B','{"A":"2","B":"3","C":"4","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Day after Friday?','B','{"A":"Thursday","B":"Saturday","C":"Sunday","D":"Monday"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option B','B','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '7×2+1=?','B','{"A":"14","B":"15","C":"16","D":"17"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 3,9,27,?','C','{"A":"54","B":"72","C":"81","D":"90"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Definately","B":"Definitely","C":"Definetly","D":"Definatly"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Pen","B":"Book","C":"Pencil","D":"Car"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '6+4×2=?','B','{"A":"20","B":"14","C":"18","D":"16"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option A','A','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Letters in DOG','B','{"A":"2","B":"3","C":"4","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Opposite of Tall','A','{"A":"Short","B":"Long","C":"Big","D":"High"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 2,4,6,?','B','{"A":"7","B":"8","C":"10","D":"12"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Acomodate","B":"Accommodate","C":"Accomodete","D":"Acommodete"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '9+1×5=?','B','{"A":"50","B":"14","C":"10","D":"20"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option C','C','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 6,12,24,?','B','{"A":"36","B":"48","C":"60","D":"72"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which is fruit?','C','{"A":"Carrot","B":"Potato","C":"Mango","D":"Onion"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Dog","B":"Cat","C":"Cow","D":"Chair"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Vowels in SCHOOL?','B','{"A":"2","B":"3","C":"4","D":"1"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct sentence','B','{"A":"We is","B":"We are","C":"We am","D":"We be"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Repeat number: 1,2,3,1,4','A','{"A":"1","B":"2","C":"3","D":"4"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Day after Sunday?','A','{"A":"Monday","B":"Tuesday","C":"Friday","D":"Saturday"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option D','D','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '5×5+5=?','B','{"A":"25","B":"30","C":"35","D":"20"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 7,14,21,?','B','{"A":"25","B":"28","C":"30","D":"35"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Tommorow","B":"Tomorrow","C":"Tomorow","D":"Tommorrow"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','C','{"A":"Apple","B":"Banana","C":"Carrot","D":"Mango"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '4+6×2=?','B','{"A":"20","B":"16","C":"14","D":"18"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option A','A','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Letters in SUN','B','{"A":"2","B":"3","C":"4","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Opposite of Fast','C','{"A":"Quick","B":"Rapid","C":"Slow","D":"Speed"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 1,3,5,?','B','{"A":"6","B":"7","C":"8","D":"9"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Becouse","B":"Because","C":"Beacause","D":"Beacuse"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '6+2×4=?','B','{"A":"32","B":"14","C":"16","D":"18"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option B','B','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 2,6,18,?','B','{"A":"36","B":"54","C":"72","D":"90"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Which is animal?','B','{"A":"Car","B":"Dog","C":"Chair","D":"Pen"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Red","B":"Blue","C":"Green","D":"Table"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Vowels in COMPUTER?','B','{"A":"2","B":"3","C":"4","D":"5"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct sentence','B','{"A":"I is","B":"I am","C":"I are","D":"I be"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Repeat number: 5,6,7,5,8','A','{"A":"5","B":"6","C":"7","D":"8"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Day after Wednesday?','A','{"A":"Thursday","B":"Friday","C":"Sunday","D":"Monday"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option C','C','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '3×3+3=?','B','{"A":"9","B":"12","C":"15","D":"18"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 10,20,40,?','C','{"A":"60","B":"70","C":"80","D":"90"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Correct spelling','B','{"A":"Frend","B":"Friend","C":"Freind","D":"Frind"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Odd one','D','{"A":"Pen","B":"Book","C":"Pencil","D":"Car"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), '8+2×2=?','B','{"A":"20","B":"12","C":"16","D":"18"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Select option D','D','{"A":"A","B":"B","C":"C","D":"D"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Letters in MOON','B','{"A":"3","B":"4","C":"5","D":"2"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Opposite of Up','A','{"A":"Down","B":"Above","C":"High","D":"Top"}');
INSERT INTO QuizQuestions (Id, QuestionText, CorrectAnswer, OptionsJson) VALUES (NEWID(), 'Next: 3,6,9,?','C','{"A":"10","B":"11","C":"12","D":"13"}');
