
ALTER TABLE QuizQuestions
ADD CONSTRAINT DF_QuizQuestions_Id
DEFAULT NEWID() FOR Id;

ALTER TABLE AuditLogs
ADD CONSTRAINT DF_AuditLogs_Id
DEFAULT NEWID() FOR Id;

ALTER TABLE Competitions
ADD CONSTRAINT DF_Competitions_Id
DEFAULT NEWID() FOR Id;

ALTER TABLE QuizAnswers
ADD CONSTRAINT DF_QuizAnswers_Id
DEFAULT NEWID() FOR Id;

ALTER TABLE QuizSessions
ADD CONSTRAINT DF_QuizSessions_Id
DEFAULT NEWID() FOR Id;

CREATE TABLE SentimentAnalysis
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),

    UserId UNIQUEIDENTIFIER NOT NULL,
    QuizSessionId UNIQUEIDENTIFIER NOT NULL,

    SubmissionText NVARCHAR(MAX) NOT NULL,
    WordCount INT NOT NULL,

    SentimentScore FLOAT NOT NULL,
    ScoreCategory NVARCHAR(50) NOT NULL,

    ReferenceNumber UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),

    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()

    -- Foreign Keys
    CONSTRAINT FK_SentimentAnalysis_User 
        FOREIGN KEY (UserId) REFERENCES Users(Id),

    CONSTRAINT FK_SentimentAnalysis_QuizSession 
        FOREIGN KEY (QuizSessionId) REFERENCES QuizSessions(Id)
);